#========================================
# General settings
#========================================
integration:
  party:
    connect-timeout: 5
    read-timeout: 30
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-alkt
  datasource:
    configuration:
      connection-timeout: 5000
      read-only: true
    connectionProperties: useUnicode=true;characterEncoding=utf-8;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      read-only: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        connection:
          readOnly: true
        jdbc:
          time_zone: Europe/Stockholm
        default_schema: dbo
      jakarta:
          persistence:
              schema-generation:
                database:
                  action: validate
  security:
    oauth2:
      client:
        registration:
          party:
            authorization-grant-type: client_credentials
            provider: party
