#========================================
# General settings
#========================================
integration:
  party:
    connect-timeout: 5
    read-timeout: 30
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-alkt
  cache:
    cache-names: partyIds, legalIds
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=86400s
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=AlkTSundsvall;trustServerCertificate=true
    username: SA
    password: P@ssword
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
          persistence:
              schema-generation:
                create-source: metadata
                database:
                  action: validate
                scripts:
                  action: create
                  create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        registration:
          party:
            authorization-grant-type: client_credentials
            provider: party

