#========================================
# General settings
#========================================
integration:
  party:
    connect-timeout: 5
    read-timeout: 30
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-alkt
  cache:
    cache-names: partyIds, legalIds
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=86400s
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=AlkTSundsvall;trustServerCertificate=true
    username: SA
    password: P@ssword
    hikari:
      read-only: true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        hbm2ddl:
          schema-generation:
            script:
              append: false
        default_schema: dbo
      jakarta:
          persistence:
              schema-generation:
                create-source: metadata
                database:
                  action: validate
                scripts:
                  action: create
                  create-target: target/database/generated-schema.sql
    database-platform: org.hibernate.dialect.SQLServerDialect
  security:
    oauth2:
      client:
        registration:
          party:
            authorization-grant-type: client_credentials
            provider: party

