#========================================
# Test profile settings (junit tests)
#========================================
integration:
  party:
    url: http://url.com
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    hikari:
      maximum-pool-size: 2
    url: jdbc:tc:sqlserver:2019-CU28-ubuntu-20.04:///
  security:
    oauth2:
      client:
        registration:
          party:
            client-id: override
            client-secret: override
        provider:
          party:
            token-uri: http://url.com/token
  sql:
    init:
      data-locations: classpath:db/initialize.sql, classpath:db/schema.sql, classpath:db/testdata.sql
      encoding: utf-8
      mode: always
